### ISSUE TITLE
Не стоит сравнивать числа double

### ISSUE THREAD

**Issue by spogozhev** [yakupchik/Homeworks#2]
https://github.com/yakupchik/Homeworks/blob/e87c3c9f595c21e503a0c73ff46eb173f5b8238e/fun_f(x)%3D0.cpp#L15
Не стоит сравнивать числа double на равенство 0. В данном случае необходимо сравнивать с точностью до некоторого eps, например, eps=1e-6.

**Comment by yakupchik** [comment]
А как это сделать?
